package com.example.state

object AppStrings {
    // App Branding & Global Header
    fun cine(lang: AppLanguage) = "Cine"
    fun stream(lang: AppLanguage) = "Stream"
    fun adminPanel(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "Admin Panel" else "Admin Panel"
    fun adminPortal(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "لوحة التحكم الإدارية" else "Admin Portal"
    fun adminLetter(lang: AppLanguage) = "A"
    fun onlineStatus(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "متصل" else "Online"
    fun navigationMenu(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "القائمة الرئيسية" else "Navigation Menu"

    // Navigation Screens
    fun dashboard(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "لوحة التحكم" else "Dashboard"
    fun users(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "المستخدمين" else "Users"
    fun appUpdates(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تحديثات التطبيق" else "App Updates"
    fun extensionsUpdates(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تحديثات الإضافات" else "Extensions Hub"
    fun globalConfig(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الإعدادات العامة" else "Global Config"
    fun notifications(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الإشعارات" else "Notifications"
    fun settings(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الإعدادات" else "Settings"
    fun diagnostics(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "فحص وتشخيص" else "Diagnostics"
    fun auditLogs(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "سجلات الأمان" else "Audit Logs"
    fun reports(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "بلاغات المستخدمين" else "User Reports"
    fun profile(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الملف الشخصي" else "Profile"
    fun logout(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تسجيل الخروج" else "Sign Out"

    // Subtitles
    fun usersSubtitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إدارة المشتركين والصلاحيات" else "Subscribers & Permissions"
    fun appUpdatesSubtitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "نشر تحديثات OTA لعملاء التطبيق" else "Publish OTA APK releases"
    fun globalConfigSubtitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "وضع الصيانة، حماية DRM، والسياسات" else "Maintenance, DRM & Policies"
    fun notificationsSubtitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إرسال إشعارات جماعية ومخصصة" else "Push Broadcasts"
    fun extensionsSubtitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إضافات ومصادر الكشط" else "APK Scrapers & Modules"
    fun reportsSubtitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "متابعة مشاكل البث وبلاغات الأعطال" else "Review client issues & bugs"
    fun settingsSubtitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تفضيلات ومظهر التطبيق" else "Appearance & Preferences"
    fun profileSubtitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "بيانات حساب المشرف" else "Admin account settings"
    fun auditLogsSubtitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "سجلات الأمان والأحداث" else "Security & Audit events"
    fun diagnosticsSubtitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "فحص السجلات والأعطال الحية" else "Live crash & log viewer"
    fun userDetailSubtitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تعديل القيود والصلاحيات" else "Account constraints"

    // Common Actions
    fun saveChanges(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حفظ التغييرات" else "Save Changes"
    fun save(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حفظ" else "Save"
    fun cancel(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إلغاء" else "Cancel"
    fun confirm(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تأكيد" else "Confirm"
    fun delete(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حذف" else "Delete"
    fun back(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "رجوع" else "Back"
    fun refresh(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تحديث" else "Refresh"
    fun search(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "بحث..." else "Search..."
    fun reset(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إعادة ضبط" else "Reset"
    fun copy(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "نسخ" else "Copy"
    fun copied(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تم النسخ بنجاح" else "Copied successfully"
    fun close(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إغلاق" else "Close"
    fun edit(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تعديل" else "Edit"
    fun add(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إضافة" else "Add"
    fun system(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "النظام" else "SYSTEM"
    fun welcomeAdmin(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "مرحباً بك، المشرف" else "Welcome back, Admin"
    fun adminAccount(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حساب المشرف" else "Admin Account"

    // Users Screen (Dashboard)
    fun addUser(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إضافة مستخدم" else "Add User"
    fun totalUsers(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إجمالي المستخدمين" else "Total Users"
    fun activeNow(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "نشط الآن" else "Active Now"
    fun proUsers(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "مستخدمين PRO" else "PRO Users"
    fun inactive(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "غير نشط" else "Inactive"
    fun searchUsersPlaceholder(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "... البحث بالاسم، البريد الإلكتروني أو الـ UID" else "Search by name, email or UID..."
    fun filterAll(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الكل" else "All"
    fun filterActive(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "نشط" else "Active"
    fun filterInactive(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "غير نشط" else "Inactive"
    fun filterPro(lang: AppLanguage) = "PRO"
    fun filterBanned(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "محظور" else "Restricted"
    fun sortNewestFirst(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الأحدث أولاً" else "Newest First"
    fun sortRecent(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "النشاط الأخير" else "Recent"
    fun sortName(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الاسم (أ - ي)" else "Name (A-Z)"
    fun userListTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "قائمة المستخدمين" else "User List"
    fun userCountBadge(count: Int, lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "$count مستخدمين" else "$count Users"
    fun neverLoggedIn(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "لم يسبق له الدخول" else "Never logged in"
    fun activeStatus(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "نشط" else "Active"
    fun inactiveStatus(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "غير نشط" else "Inactive"
    fun adminBadge(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "أدمن" else "ADMIN"
    fun proBadge(lang: AppLanguage) = "PRO"
    fun restrictedBadge(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "مقيد" else "RESTRICTED"
    fun viewDetails(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "عرض التفاصيل والصلاحيات" else "View Details & Permissions"
    fun upgradeToPro(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "ترقية إلى حساب PRO" else "Upgrade to PRO"
    fun revokePro(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إلغاء اشتراك PRO" else "Revoke PRO"
    fun restrictUser(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حظر / تقييد المستخدم" else "Restrict / Ban User"
    fun unbanUser(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "فك الحظر عن المستخدم" else "Unban User"
    fun deleteUser(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حذف المستخدم" else "Delete User"
    fun confirmDeleteUserTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تأكيد حذف المستخدم" else "Confirm User Deletion"
    fun confirmDeleteUserMsg(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "هل أنت متأكد من رغبتك في حذف هذا المستخدم نهائياً؟ لا يمكن التراجع عن هذا الإجراء." else "Are you sure you want to permanently delete this user? This action cannot be undone."
    fun addNewUserDialogTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إضافة مستخدم جديد" else "Add New User"
    fun username(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "اسم المستخدم" else "Username"
    fun email(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "البريد الإلكتروني" else "Email Address"
    fun optionalPassword(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "كلمة المرور (اختياري)" else "Password (Optional)"
    fun proAccountCheckbox(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تفعيل اشتراك PRO فورياً" else "Enable PRO Plan Immediately"
    fun adminRoleCheckbox(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "منح صلاحيات المشرف (Admin)" else "Grant Administrator Privileges"
    fun noUsersMatch(query: String, lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "لا توجد نتائج مطابقة لـ '$query'" else "No users match '$query'"
    fun noUsersYet(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "لا يوجد مستخدمين مسجلين حتى الآن" else "No registered users yet"
    fun usersAutoSyncDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "سيتم مزامنة حسابات عملاء CineStream تلقائياً هنا في الوقت الفعلي" else "CineStream client users will automatically synchronize here in real time"
    fun resetSearchAndFilters(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إعادة ضبط البحث والتصفية" else "Reset Search & Filters"
    fun syncingUsers(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "جاري مزامنة مستخدمي CineStream..." else "Syncing CineStream users..."

    // App Updates (OTA) Screen
    fun appUpdatesTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تحديثات التطبيق (OTA)" else "App Updates (OTA)"
    fun currentRelease(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الإصدار الحالي في الإنتاج" else "Current Production Release"
    fun configureNewRelease(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تهيئة ونشر تحديث جديد" else "Configure & Publish New Release"
    fun versionNameField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "اسم الإصدار (مثل 2.5.0)" else "Version Name (e.g. 2.5.0)"
    fun versionCodeField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "رقم البناء الداخلي (Build Code)" else "Build Code (e.g. 25)"
    fun apkDownloadUrlField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "رابط تحميل ملف APK المباشر" else "Direct APK Download URL"
    fun apkSha256Field(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "بصمة التحقق والتشفير (SHA-256)" else "SHA-256 Checksum (Optional)"
    fun mandatoryUpdate(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "فرض التحديث الإجباري" else "Mandatory Update"
    fun mandatoryUpdateDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "منع فتح التطبيق حتى يتم تحديثه" else "Block older versions until updated"
    fun minVersionCodeField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الحد الأدنى لرقم الإصدار المدعوم" else "Minimum Supported Build Code"
    fun releaseNotesField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "سجل التغييرات والميزات الجديدة" else "Release Notes & Changelog"
    fun publishReleaseNow(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "نشر التحديث لجميع المستخدمين" else "Publish Release Now"
    fun updatePreviewTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "معاينة رسالة التحديث للمستخدم" else "User-Facing Update Dialog Preview"
    fun confirmPublishDialogTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تأكيد نشر تحديث التطبيق؟" else "Confirm OTA Release Publish?"
    fun confirmPublishDialogMsg(versionName: String, versionCode: String, lang: AppLanguage) = 
        if (lang == AppLanguage.ARABIC) "سيتم إشعار جميع أجهزة المستخدمين فورياً بالإصدار الجديد $versionName (Build $versionCode)." 
        else "All user devices will be immediately notified of version $versionName (Build $versionCode)."
    fun uploadApkFromDevice(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "رفع ملف APK من جهازك" else "Upload APK from Device"
    fun uploadApkDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "اختيار ملف التحديث لحساب بصمة SHA-256 ورفعه إلى السيرفر تلقائياً" else "Pick APK to auto-calculate SHA-256 and upload to server"
    fun analyzingApk(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "جاري فحص الملف وحساب بصمة SHA-256..." else "Analyzing APK & computing SHA-256..."
    fun uploadingApk(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "جاري رفع ملف APK إلى السيرفر..." else "Uploading APK to server..."
    fun uploadApkSuccess(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تم رفع ملف APK وحساب البصمة بنجاح!" else "APK uploaded & SHA-256 computed successfully!"
    fun hashCalculatedNotice(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تم حساب بصمة التشفير SHA-256 بنجاح. يمكنك إدخال رابط التحميل يدوياً." else "SHA-256 computed successfully. You may enter download link manually."
    fun broadcastNotificationToggle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إرسال إشعار فوري لجميع المستخدمين بالتحديث" else "Broadcast push alert to all users"
    fun broadcastNotificationDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إرسال تنبيه جماعي فوري ينبه الأجهزة بوجود الإصدار الجديد" else "Send instant push broadcast to all active devices"
    fun restoreCurrentValues(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "استعادة بيانات الإصدار الحالي" else "Restore Current Values"

    // Global Config Screen
    fun globalConfigTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الإعدادات والسياسات العامة" else "Global Config & Policies"
    fun maintenanceSection(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "وضع الصيانة العام" else "Global Maintenance Mode"
    fun maintenanceToggle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تفعيل وضع الصيانة" else "Enable Maintenance Mode"
    fun maintenanceToggleDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إيقاف خوادم البث مؤقتاً وعرض شاشة الصيانة" else "Temporarily pause streaming and show maintenance screen"
    fun maintenanceTitleField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "عنوان شاشة الصيانة" else "Maintenance Screen Title"
    fun maintenanceMessageField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "رسالة الصيانة للمستخدمين" else "Maintenance Message"
    fun minClientVersionField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الحد الأدنى لإصدار التطبيق المطلوب" else "Minimum Required Client Version"
    fun securityDrmSection(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حماية المحتوى والأمان (DRM)" else "Content Protection & Security (DRM)"
    fun antiTamperToggle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "فحص سلامة الحزمة (Anti-Tamper)" else "Anti-Tamper & Signature Verification"
    fun antiTamperDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "منع تشغيل نسخ التطبيق المعدلة أو غير الرسمية" else "Block modified or tampered client APKs"
    fun screenshotBlockToggle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حظر لقطات وتسجيل الشاشة (DRM Flag Secure)" else "Block Screenshots & Recording (FLAG_SECURE)"
    fun screenshotBlockDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حظر تسجيل الشاشة لحماية البث من القرصنة" else "Prevent screen recording to protect streams"
    fun rootDetectionToggle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حظر الأجهزة المروتة (Root Detection)" else "Root & Emulator Detection"
    fun rootDetectionDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تقييد الأجهزة التي تمتلك صلاحيات Root" else "Restrict access on rooted and emulated devices"
    fun offlinePolicySection(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "سياسات التحميل بدون إنترنت" else "Offline Download Policies"
    fun downloadExpiryField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "صلاحية الفيديوهات المحملة (بالأيام)" else "Downloaded Media Expiry (Days)"
    fun maxOfflineDownloadsField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الحد الأقصى للملفات المحملة لكل جهاز" else "Max Offline Downloads per Device"
    fun adPolicySection(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "سياسات الإعلانات للمستخدم المجاني" else "Ad Policies for Free Tier"
    fun adIntervalField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الفترة الزمنية بين الإعلانات الإجبارية (بالدقائق)" else "Interval Between Forced Ads (Minutes)"
    fun saveGlobalPolicies(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حفظ السياسات العامة" else "Save Global Policies"
    fun policiesSavedSuccess(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تم حفظ الإعدادات بنجاح" else "Policies saved successfully"

    // Extensions Screen
    fun extensionsTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تحديثات ومصادر الكشط" else "Scraper Modules & Extensions"
    fun registeredScrapers(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الكاشطات المسجلة في التطبيق" else "Registered Scraper Modules"
    fun addExtension(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إضافة كاشط جديد" else "Add Scraper Module"
    fun editExtension(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تعديل الكاشط" else "Edit Scraper Module"
    fun deleteExtension(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حذف الكاشط" else "Delete Scraper Module"
    fun confirmDeleteExtTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تأكيد حذف الكاشط" else "Confirm Scraper Deletion"
    fun confirmDeleteExtMsg(name: String, lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "هل أنت متأكد من حذف كاشط '$name' نهائياً؟" else "Are you sure you want to delete '$name' scraper?"
    fun extensionNameField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "اسم الكاشط أو المصدر" else "Scraper Name"
    fun extensionPackageField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "معرف الحزمة (Package ID)" else "Package ID"
    fun extensionVersionField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إصدار الكاشط (Version)" else "Extension Version"
    fun extensionApkUrlField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "رابط ملف التحميل (DEX / APK)" else "Download File URL (DEX/APK)"
    fun extensionEnabledToggle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تفعيل الكاشط في التطبيق" else "Enable Scraper in Client"
    fun directJsonEditor(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "المحرر السريع لكود الـ JSON" else "Direct Extensions JSON Editor"
    fun saveJsonConfig(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حفظ كود الـ JSON" else "Save JSON Config"
    fun noExtensionsFound(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "لا توجد إضافات مسجلة حالياً" else "No extensions registered yet"

    // Notifications Screen
    fun notificationsTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إرسال الإشعارات" else "Push Notifications"
    fun sendBroadcast(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إنشاء إشعار جديد" else "Create New Broadcast"
    fun notificationHistory(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "سجل الإشعارات المرسلة" else "Notification History"
    fun notifTitleField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "عنوان الإشعار" else "Notification Title"
    fun notifBodyField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "نص الإشعار" else "Notification Message"
    fun targetAudience(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الفئة المستهدفة" else "Target Audience"
    fun targetAllUsers(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "جميع المستخدمين" else "All Users"
    fun targetProUsers(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "مشتركو PRO فقط" else "PRO Members Only"
    fun targetFreeUsers(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "المستخدمون المجانيون" else "Free Tier Users"
    fun deepLinkUrlField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "رابط التوجيه المباشر (اختياري)" else "Deep Link URL (Optional)"
    fun sendNow(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إرسال الإشعار الآن" else "Send Broadcast Now"
    fun sending(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "جاري الإرسال..." else "Sending..."
    fun confirmSendNotifTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تأكيد إرسال الإشعار الجماعي" else "Confirm Push Broadcast"
    fun confirmSendNotifMsg(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "سيتم إرسال هذا التنبيه فورياً إلى الأجهزة المحددة." else "This push alert will be immediately delivered to selected devices."
    fun noNotifHistory(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "لا توجد إشعارات سابقة في السجل" else "No sent notifications in history"

    // Settings Screen
    fun settingsTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إعدادات التطبيق" else "App Settings"
    fun appearance(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "المظهر والتصميم" else "Appearance & Theme"
    fun darkTheme(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "المظهر الداكن (Dark)" else "Dark Theme"
    fun darkThemeDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "وضع مريح للعين وألوان داكنة أنيقة" else "Comfortable dark palette for nighttime"
    fun lightTheme(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "المظهر الفاتح (Light)" else "Light Theme"
    fun lightThemeDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "وضع مشرق وعالي التباين" else "Crisp high-contrast bright palette"
    fun language(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "لغة التطبيق" else "App Language"
    fun languageDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "يدعم التطبيق اللغتين العربية والإنجليزية" else "Switch between Arabic (RTL) and English (LTR)"
    fun notificationPreferences(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تفضيلات الإشعارات" else "Notification Preferences"
    fun enableNotifications(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تفعيل الإشعارات" else "Enable In-App Notifications"
    fun soundAlerts(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تنبيهات صوتية" else "Sound Alerts"
    fun vibration(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الاهتزاز عند الأحداث" else "Vibration Feedback"
    fun testNotification(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إرسال إشعار تجريبي" else "Send Test Notification"
    fun testNotifSentMsg(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تم إرسال الإشعار التجريبي بنجاح!" else "Test notification sent successfully!"
    fun systemInfo(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "معلومات النظام والاتصال" else "System Information"
    fun appVersion(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إصدار لوحة التحكم" else "Admin Portal Version"
    fun connectedProject(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "مشروع Firebase المتصل" else "Connected Firebase Project"
    fun systemDiagnosticsBtn(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "فتح فحص وتشخيص النظام" else "Open System Diagnostics"

    // User Detail Screen
    fun userDetailTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تفاصيل المستخدم والصلاحيات" else "User Details & Permissions"
    fun userInfoSection(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "المعلومات الأساسية والحساب" else "Account & Profile Details"
    fun userPermissionsSection(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "صلاحيات استخدام التطبيق" else "App Feature Permissions"
    fun canWatch(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "صلاحية المشاهدة والبث المباشر" else "Watching & Streaming Access"
    fun canWatchDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "السماح للمستخدم بمشاهدة الأفلام والمسلسلات" else "Allow user to watch video streams"
    fun canDownload(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "صلاحية التحميل بدون إنترنت" else "Offline Download Access"
    fun canDownloadDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "السماح بتحميل الحلقات والأفلام للهاتف" else "Allow offline video downloads"
    fun canChat(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "صلاحية الدردشة وغرف النقاش" else "Chat & Community Rooms"
    fun canChatDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "السماح بالمشاركة في محادثات وغرف المشاهدة الجماعية" else "Allow participating in public chats"
    fun canStory(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "صلاحية نشر القصص ومقاطع الفيديو" else "Stories & Clip Publishing"
    fun canStoryDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "السماح بنشر الستوري ومقاطع الفيديو القصيرة" else "Allow publishing user stories and clips"
    fun canP2P(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "صلاحية المشاركة عبر شبكة P2P المحلية" else "Local P2P Share Access"
    fun canP2PDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "السماح بنقل الملفات محلياً بدون إنترنت" else "Allow offline peer-to-peer file sharing"
    fun roleAndSubscription(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الرتبة ونوع الاشتراك" else "Role & Subscription Tier"
    fun isProSubscriber(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "اشتراك بريميوم (PRO)" else "Premium PRO Subscriber"
    fun isAdministrator(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "صلاحيات المشرف (Administrator)" else "Administrator Privileges"
    fun grantAdminToggle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "صلاحيات المدير الكاملة (Administrator)" else "Full Administrator Privileges"
    fun saveUserPermissions(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حفظ صلاحيات المستخدم" else "Save User Permissions"

    // Diagnostics & Logs
    fun diagnosticsTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "فحص وتشخيص النظام" else "System Diagnostics"
    fun auditLogsTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "سجلات الأمان والأحداث" else "Security & Audit Logs"
    fun profileTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الملف الشخصي للمشرف" else "Admin Profile"
    fun emailField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "البريد الإلكتروني" else "Email Address"
    fun uidField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "معرف الحساب (UID)" else "Account UID"
    fun roleField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الرتبة" else "Role"
    fun createdAtField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تاريخ الإنشاء" else "Created At"

    // Login Screen
    fun loginTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تسجيل الدخول للإدارة" else "Admin Sign In"
    fun loginSubtitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "أدخل بيانات حساب المشرف للمتابعة" else "Sign in to access CineStream portal"
    fun adminEmail(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "البريد الإلكتروني" else "Admin Email"
    fun password(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "كلمة المرور" else "Password"
    fun rememberMe(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تذكرني" else "Remember me"
    fun forgotPassword(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "نسيت كلمة المرور؟" else "Forgot Password?"
    fun signInButton(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "دخول لوحة التحكم" else "Sign In"
    fun signInWithGoogle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الدخول بواسطة Google" else "Sign in with Google"
    fun orDivider(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "أو" else "OR"
    fun restrictedAccess(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "منطقة محظورة • للمشرفين المصرح لهم فقط" else "Restricted Access • Authorized Administrators Only"
    fun resetPasswordTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "استعادة كلمة المرور" else "Reset Password"
    fun resetPasswordDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "أدخل بريدك الإلكتروني كمسؤول وسنرسل لك رابط إعادة تعيين كلمة المرور." else "Enter your administrator email address. A reset link will be sent to your inbox."
    fun sendResetLink(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إرسال الرابط" else "Send Link"
    fun loading(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "جاري التحميل..." else "Loading..."
    fun processing(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "جاري المعالجة..." else "Processing..."
    fun saving(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "جاري الحفظ..." else "Saving..."
}
